### ISSUE TITLE
Better support citation of cookbooks

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/cookbook-gallery#15]
Per the [discussion](https://github.com/ProjectPythia/projectpythia.github.io/discussions/258) started by @brian-rose there are a few things we might do to facilitate citation and giving credit to authors of cookbooks. Some things we might consider:

1. Add an author(s) field to the template
2. Display authors in the gallery "cards"
3. Facilitate (provide guidance) on optionally creating a DOI for the notebook and display the DOI in cards and template.

**Comment by brian-rose** [comment]
I will open a PR to add the author field to the template.

**Comment by brian-rose** [comment]
I see that the [EarthCube peer-reviewed notebooks](https://www.earthcube.org/notebooks) use Zenodo to mint DOIs. I've done this for other projects, and it's pretty straightforward to set it up so that a unique DOI is generated for each tagged release of a source repository on GitHub.

This is probably the way to go with Cookbooks too. When a Cookbook is "accepted" following review, a tagged Release can be created for the GitHub repo. This will then trigger the minting of a DOI (and archiving of the tagged version of the repo on Zenodo's archive for posterity). Cookbook authors can decide whether recent revisions to their repo are sufficient to warrant minting a new GitHub release and thus an updated DOI. And users of the Cookbook can easily cite it in their own work using the DOI. This is all pretty straightforward.

On the other hand, it's always struck me as slightly perverse to use this method (citing the *code repository*) as a stand-in for citing the *scientific content*. The reason is that the source repository contains all kinds of code and infrastructure for *building* the book, in addition to the actual *content* of the book. 

In a perfect world, there would be a simple way to cite the *rendered book* as it appears on https://cookbooks.projectpythia.org (but with a stable-for-all-time citation), and *also* but *seperately* a way to cite the infrastructure that builds the book.

I'm probably over-thinking this though.

**Comment by brian-rose** [comment]
While I'm on this subject, I should say that all the same thing applies to Foundations. We really ought to set up a DOI for the Foundations repo so that it is citable too. I'll open that issue now.

**Comment by clyne** [comment]
I think automating DOI minting would be another incentive for folks to contribute to our gallery as opposed to putting it up on their own site somewhere. This is another value add that our infrastructure can provide.

**Comment by brian-rose** [comment]
Elevating this to high priority so we can get something done on this prior to the summer 2023 hackathon.

We can "practice" the DOI minting mechanism on Foundations: https://github.com/ProjectPythia/pythia-foundations/issues/309, https://github.com/ProjectPythia/pythia-foundations/issues/344

**Comment by jukent** [comment]
Will work on this once we've agreed on the citation method for foundations.
